name = "astro-100k"
main = "dist/_worker.js"
compatibility_date = "2025-12-18"
workers_dev = true
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = "./dist"
binding = "ASSETS"

[[kv_namespaces]]
binding = "CONFIG"
id = "3db79397c0de484f8ac3f07e59cf57dd"
#remote = true

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "rangefs"
#remote = true

#[[routes]]
#pattern = "astro-100k.proc.io"
#custom_domain = true
